development:
  adapter: postgresql
  encoding: unicode
  database: new_assignment
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: new_assignment_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: new_assignment_pro
  pool: 5
  username: postgres
  password: postgres